const mongoose = require('mongoose');

const taskSchema = new mongoose.Schema(
  {
    client: { type: mongoose.Schema.Types.ObjectId, ref: 'Client', required: false },
    taskType: {
      type: String,
      enum: ['Client Task', 'Common Task'],
      default: 'Common Task'
    },
    department: {
      type: String,
      enum: ['GST', 'Book Keeping', 'IT Filing', 'Registration', 'Income Tax', 'Accounts', 'Administration'],
      required: true
    },
    taskName: { type: String, required: true },
    priority: {
      type: String,
      enum: ['Low', 'Medium', 'High', 'Critical'],
      default: 'Medium'
    },
    assignedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    assignedEmployee: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    assignedDate: { type: Date, default: Date.now },
    dueDate: { type: Date, required: true },
    reminderDays: { type: Number, default: 3 },
    repeat: {
      type: String,
      enum: ['Monthly', 'Quarterly', 'Yearly', 'One Time'],
      default: 'One Time'
    },
    status: {
      type: String,
      enum: ['Assigned', 'In Progress', 'Completed', "Can't Complete", 'Pending', 'Waiting', 'On Hold', 'Cancelled'],
      default: 'Assigned'
    },
    remarks: { type: String },
    attachment: { type: String },
    isAutoGenerated: { type: Boolean, default: false },
    parentTaskId: { type: mongoose.Schema.Types.ObjectId, ref: 'Task' },
    isBilled: { type: Boolean, default: false },
    invoice: { type: mongoose.Schema.Types.ObjectId, ref: 'Invoice' },
    invoiceNumber: { type: String }
  },
  { timestamps: true }
);

module.exports = mongoose.model('Task', taskSchema);
